### ISSUE TITLE
Week 5 & 7 - Crossover Evaluation

### ISSUE THREAD

**Issue by PranaviInukurti** [samayasankuratri/flask_portfolio#56]
Total Score: /6
Requirements Score: /6
- [x] Evaluation of Crossover Team PBL key features

- [x] Evaluation of Github Pages, Jekyll, WIKI - focus will be on quality of Vocabulary from Week 6 as key review item

- [x] Evaluation of Sassy / Bootstrap - under the hood on CSS usage and capitalizing on Bootstrap features, as well as runtime quality

- [x] Evaluation of Async Operation - runtime and under the hood usage of JavaScript and Fetch, as well as how things are updated on screen

- [x] Evaluation of CRUD in Database - runtime and behind the scenes using CRUD operations, as well as progress on database personalization

Extra Credit Score: /2

- [x] Evaluation of Blueprint illustration/demonstration, effectiveness of removing code out of central main.py and test of routes

- [ ] Evaluation of Filtering/Searching data, this is Filtering data from Database, this can complement Async operation

**Comment by Reinhardtlotter** [comment]
PBL: 1/1
Jekyll and wiki: 0.75/1
Sassy and bootstrap: 1/1
Async operation: 0.5/1
Crud: 1/1
Blueprint:1/1
Total:5.25/6
